import {environment} from "../../environments/environment";

export const constant: any =
    {
        BASE_API: location.protocol + '//' + environment.base_api + '/api/',
        //BASE_API: '//' + environment.base_api + '/api/',
        FILE_URL: location.protocol + '//' + environment.base_api + '/files/',
        PRIVATE_URL: location.protocol + '//' + environment.base_api + '/member/image',
        FILE_URL_RESIZE_AVATAR: location.protocol + '//' + environment.base_api + '/files/Media/catalog/cache/images/200x200/',
        FILE_URL_RESIZE_SLIDESHOW: location.protocol + '//' + environment.base_api + '/files/Media/catalog/cache/images/400x0/',
        FILE_URL_RESIZE_BANNER: location.protocol + '//' + environment.base_api + '/files/Media/catalog/cache/images/1000x0/',
        FILE_URL_RESIZE_PLAN_BLOCK: location.protocol + '//' + environment.base_api + '/files/Media/catalog/cache/images/0x200/',

        BASE_WEB: location.protocol + '//' + environment.base_web + '/',
        //limit record
        LIMIT_RECORD: 10,
        LIMIT_RECORD_ADMIN_TOP: 5,

        // User group
        GROUP_ADMIN: 1,
        GROUP_USER: 2,
        //Classsification booking
        BOOK_RESERVATION: 'Book reservation',
        REQUEST_RESERVATION: 'Request reservation',
        //Guider Select
        GUIDER_SELECT_US: 'Travel Guide select',
        GUIDER_SELECT_JP: '旅ガイドを選択してください',
        //Status booking
        BOOKING_NOT_PAYMENT: 0,
        REQUESTING_GUIDER: 1,
        GUIDER_APPROVED: 2,
        AFTER_EXECUTE: 3,
        REQUEST_REVIEW: 4,
        REVIEWED: 5,
        CANCEL: 9,
        //Status request
        RECRUITING_REQUEST: 1,
        UNDER_NEGOTIATION: 2,
        IMPLEMENT_WAITING: 3,
        REQUEST_CLOSED: 4,
        IMPLEMENTED: 5,

        OFFER: 2,
        WAITING_PROCESSING: 3,
        NO_SUGGESTIONS: 4,
        SUGGESTIONS: 5,
        //Suggestions plan
        NEGOTIATION: 5,
        DECLINE: 6,
        DECIDED: 7,
        PROPOSAL_COLLECTION: 8,
        //Approval
        REQUEST_APPROVAL: 4,
        NOT_YET: 1,
        APPROVAL: 2,
        NON_APPROVAL: 3,
        //Status request
        REQUEST_NO_SUGGESTIONS: 4,
        //booking review
        BOOKING_REVIEW_CONFIRM: 0,
        BOOKING_REVIEW_APPROVAL: 1,
        BOOKING_REVIEW_NON_APPROVAL: 2,


        // Status member
        MEMBER_IS_USER: 1,
        MEMBER_NOT_CONFIRM: 2,
        MEMBER_NOT_CARD: 3,
        MEMBER_RECEIVED: 4,
        MEMBER_REJECT: 5,
        //Status type member
        MEMBER_USER: 1,
        MEMBER_GUIDER: 2,

        // Gender
        Male: 1,
        Female: 2,

        // mail magazine option member
        Send: 1,
        Not_Send: 2,
        // is agree conditions
        NOT_AGREE_CONDITIONS: 0,
        IS_AGREE_CONDITIONS: 1,

        // Top language Id
        TOP_LANGUAGE_ID: 1,
        JA_LANGUAGE_ID: 1,
        EN_LANGUAGE_ID: 2,
        //Current unit
        CURRENCY_UNIT_DEFAULT: 1,
        COUNTRY_DEFAULT: 1,
        //Date of week
        MONDAY: "月",
        THURSDAY: "火",
        TUESDAY: "水",
        WEDNESDAY: "木",
        FRIDAY: "金",
        SATURDAY: "土",
        SUNDAY: "日",
        //Status true or false
        TRUE: 1,
        FALSE: 0,
        NOT_COME: 2,
        //Sort
        CREATED_AT: 1,
        PRICE: 2,
        //Type country
        COUNTRY_IS_SEARCH: 1,
        COUNTRY_IS_PROFILE: 2,
        // display on top
        display_top: {
            1: 'true',
            0: 'false'
        },
        //default language prefix
        DEFAULT_LANGUAGE_PREFIX: 'ja',
        DEFAULT_LANGUAGE_URL: '',
        EN_LANGUAGE_URL: 'en',
        // mail magazine option member
        Mail_magazine_option: {
            1: 'Receive via email',
            2: 'No via email',
        },
        //page back
        PLAN_ADD: 1,
        REQUEST_ADD: 2,
        REQUEST_DETAIL: 3,
        GUIDE_DETAIL: 4,
        TOUR_DETAIL: 5,
        BOOKING_PLAN: 6,

        User: {
            group: {
                1: 'Group admin',
                2: 'Group member',
            },
            gender: {
                1: 'Male',
                2: 'Female',
            },
        },
        Booking: {
            status: {
                1: 'Request sent',
                2: 'Confirmed',
                3: 'After execute',
                4: 'Request review',
                5: 'Reviewed',
                9: 'Cancel'
            },
            status_backend: {
                1: 'Requesting',
                2: 'Before execute',
                3: 'Execute confirm',
                4: 'Executed',
                9: 'Cancel'
            },
            user_approval: {
                1: 'Not yet',
                2: 'Approved',
                3: 'Non-approval'
            },
            guider_status: {
                1: 'Not yet',
                2: 'Approved',
                3: 'Non-approval'
            },
            review_status: {
                1: 'Approval',
                2: 'Approved',
                3: 'Non-approval'
            },
            guider_payment: {
                0: 'Not yet',
                3: 'Being processed',
                2: 'Defect',
                1: 'Done'
            },
            payment: {
                0: 'Not yet',
                1: 'Done'
            },
            classification: {
                0: 'Book reservation',
                1: 'Request reservation'
            }
        },
        Request: {
            status: {
                1: '募集中',
                2: '交渉中',
                3: '実施待ち',
                4: '募集終了',
                5: '実施済み',
                9: 'F28_キャンセル'
            }
        },
        GuiderStatus: {
            PUBLIC_OFFERING: 1,
            APPROVAL_REQUEST: 2,
            NON_APPROVAL: 3,
            STOP_PUBLIC: 4,
        },
        SuggestionPlanStatus: {
            5: 'Negotiation', // cho approve
            6: 'Decline',    // tu choi
            7: 'Decided',    // chap nhan
            8: 'Proposal collection',    // chap nhan
            9: 'Cancel',
        },
        SuggestionPlanStatusJapan: {
            5: 'F62_交渉中', // cho approve
            6: 'F62_お断り',    // tu choi
            7: 'F62_決定',    // chap nhan
            8: 'F62_提案集',    // re edit
            9: 'F62_キャンセル',//cancel
        },
        Guider: {
            time_apply: {
                TIME_REQUIRED: 1,
                RESERVE_TIME: 2,
                DAILY_RESERVATION: 3,
            },
            time_apply_text: {
                1: 'Make reservations impossible within the required time from reservation time',
                2: 'Reserve time without reservation time relation',
                3: 'Reservation should be 1 daily reservation',
            },
            status: {
                1: 'Public offering',
                2: 'Approval request',
                3: 'Non approval',
                4: 'Stop public',
            },
            status_backend: {
                1: 'Public offering',
                4: 'Stop public'
            },

        },


        Member: {
            type: {
                1: 'Traveler',
                2: 'Travel Guide',
            },
        },

        fileValidateDefault: {
            required: true,
            size: 3072, //3M
            extensions: ['jpg', 'png', 'jpeg', 'pdf']
        },

        Active: {
            1: 'Yes',
            0: 'No'
        },
        Language_display: {
            1: 'Is display',
        },

        Language_support: {
            1: 'Is support',
        },

        TimePlans: ['00:00', '01:00', '02:00', '03:00', '04:00', '05:00', '06:00', '07:00', '08:00', '09:00', '10:00', '11:00', '12:00', '13:00', '14:00', '15:00', '16:00', '17:00', '18:00', '19:00', '20:00', '21:00', '22:00', '23:00'],

        ActiveDefine: {
            YES: 1,
            NO: 0,
        },
        Currency_unit: {
            1: '¥',
            2: '$'
        },
        Japan: {
            1: '日本'
        },

        SearchParams: {
            prefecture_prefix: '',
            category_prefix: [],
            language_prefix: '',
            date_plan: ''
        },

        TitleParams: {
            language: [],
            date_plan: [],
            city: [],
            category: []
        },
        // top set time
        TimePlan: {
            Plan_hour_min: {
                0: '00 時間',
                1: '01 時間',
                2: '02 時間',
                3: '03 時間',
                4: '04 時間',
                5: '05 時間',
                6: '06 時間',
                7: '07 時間',
                8: '08 時間',
                9: '09 時間',
                10: '10 時間',
                11: '11 時間',
                12: '12 時間',
                13: '13 時間',
                14: '14 時間',
                15: '15 時間',
                16: '16 時間',
                17: '17 時間',
                18: '18 時間',
                19: '19 時間',
                20: '20 時間',
                21: '21 時間',
                22: '22 時間',
                23: '23 時間',
            },
            Plan_hour: {
                0: '00',
                1: '01',
                2: '02',
                3: '03',
                4: '04',
                5: '05',
                6: '06',
                7: '07',
                8: '08',
                9: '09',
                10: '10',
                11: '11',
                12: '12',
                13: '13',
                14: '14',
                15: '15',
                16: '16',
                17: '17',
                18: '18',
                19: '19',
                20: '20',
                21: '21',
                22: '22',
                23: '23',
            },
            Plan_min: {
                0: '00',
                1: '01',
                2: '02',
                3: '03',
                4: '04',
                5: '05',
                6: '06',
                7: '07',
                8: '08',
                9: '09',
                10: '10',
                11: '11',
                12: '12',
                13: '13',
                14: '14',
                15: '15',
                16: '16',
                17: '17',
                18: '18',
                19: '19',
                20: '20',
                21: '21',
                22: '22',
                23: '23',
                24: '24',
                25: '25',
                26: '26',
                27: '27',
                28: '28',
                29: '29',
                30: '30',
                31: '31',
                32: '32',
                33: '33',
                34: '34',
                35: '35',
                36: '36',
                37: '37',
                38: '38',
                39: '39',
                40: '40',
                41: '41',
                42: '42',
                43: '43',
                44: '44',
                45: '45',
                46: '46',
                47: '47',
                48: '48',
                49: '49',
                50: '50',
                51: '51',
                52: '52',
                53: '53',
                54: '54',
                55: '55',
                56: '56',
                57: '57',
                58: '58',
                59: '59',
            },

        },
        CountryCallingCodes: {
            'JP': '日本 (+81)',
            'CG': 'コンゴ (+242)',
            'CD': 'コンゴ民主共和国 (+243)',
            'XK': 'コソボ (+383)',
            'MK': 'マケドニア (+389)',
            'IS': 'アイスランド (+354)',
            'IE': 'アイルランド (+353)',
            'AZ': 'アゼルバイジャン (+994)',
            'AF': 'アフガニスタン (+93)',
            'US': 'アメリカ (+1)',
            'AE': 'アラブ首長国連邦 (+971)',
            'DZ': 'アルジェリア (+213)',
            'AR': 'アルゼンチン (+54)',
            'AW': 'アルバ (+297)',
            'AL': 'アルバニア (+355)',
            'AM': 'アルメニア (+374)',
            'AI': 'アンギラ (+1)',
            'AO': 'アンゴラ (+244)',
            'AG': 'アンティグア・バーブーダ (+1)',
            'AD': 'アンドラ (+376)',
            'YE': 'イエメン (+967)',
            'GB': 'イギリス (+44)',
            'IL': 'イスラエル (+972)',
            'IT': 'イタリア (+39)',
            'IQ': 'イラク (+964)',
            'IN': 'インド (+91)',
            'ID': 'インドネシア (+62)',
            'WF': 'ウォリス・フツナ (+681)',
            'UG': 'ウガンダ (+256)',
            'UA': 'ウクライナ (+380)',
            'UZ': 'ウズベキスタン (+998)',
            'UY': 'ウルグアイ (+598)',
            'EC': 'エクアドル (+593)',
            'EG': 'エジプト (+20)',
            'EE': 'エストニア (+372)',
            'ET': 'エチオピア (+251)',
            'ER': 'エリトリア (+291)',
            'SV': 'エルサルバドル (+503)',
            'AU': 'オーストラリア (+61)',
            'AT': 'オーストリア (+43)',
            'AX': 'オーランド諸島 (+358)',
            'OM': 'オマーン (+968)',
            'NL': 'オランダ (+31)',
            'BQ': 'オランダ領カリブ (+599)',
            'GH': 'ガーナ (+233)',
            'CV': 'カーボベルデ (+238)',
            'GG': 'ガーンジー (+44)',
            'GY': 'ガイアナ (+592)',
            'KZ': 'カザフスタン (+7)',
            'QA': 'カタール (+974)',
            'CA': 'カナダ (+1)',
            'GA': 'ガボン (+241)',
            'CM': 'カメルーン (+237)',
            'GM': 'ガンビア (+220)',
            'KH': 'カンボジア (+855)',
            'GN': 'ギニア (+224)',
            'GW': 'ギニアビサウ (+245)',
            'CY': 'キプロス (+357)',
            'CW': 'キュラソー (+599)',
            'GR': 'ギリシャ (+30)',
            'KI': 'キリバス (+686)',
            'KG': 'キルギス (+996)',
            'GT': 'グアテマラ (+502)',
            'GP': 'グアドループ (+590)',
            'GU': 'グアム (+1)',
            'KW': 'クウェート (+965)',
            'CK': 'クック諸島 (+682)',
            'GL': 'グリーンランド (+299)',
            'CX': 'クリスマス島 (+61)',
            'GE': 'グルジア (+995)',
            'GD': 'グレナダ (+1)',
            'HR': 'クロアチア (+385)',
            'KY': 'ケイマン諸島 (+1)',
            'KE': 'ケニア (+254)',
            'CC': 'ココス[キーリング]諸島 (+61)',
            'CR': 'コスタリカ (+506)',
            'KM': 'コモロ (+269)',
            'CO': 'コロンビア (+57)',
            'SA': 'サウジアラビア (+966)',
            'WS': 'サモア (+685)',
            'BL': 'サン・バルテルミー島 (+590)',
            'MF': 'サン・マルタン (+590)',
            'ST': 'サントメ・プリンシペ (+239)',
            'ZM': 'ザンビア (+260)',
            'PM': 'サンピエール島・ミクロン島 (+508)',
            'SM': 'サンマリノ (+378)',
            'SL': 'シエラレオネ (+232)',
            'DJ': 'ジブチ (+253)',
            'GI': 'ジブラルタル (+350)',
            'JE': 'ジャージー (+44)',
            'JM': 'ジャマイカ (+1)',
            'SG': 'シンガポール (+65)',
            'SX': 'シント・マールテン (+1)',
            'ZW': 'ジンバブエ (+263)',
            'CH': 'スイス (+41)',
            'SE': 'スウェーデン (+46)',
            'SJ': 'スバールバル諸島・ヤンマイエン島 (+47)',
            'ES': 'スペイン (+34)',
            'SR': 'スリナム (+597)',
            'LK': 'スリランカ (+94)',
            'SK': 'スロバキア (+421)',
            'SI': 'スロベニア (+386)',
            'SZ': 'スワジランド (+268)',
            'SC': 'セーシェル (+248)',
            'SN': 'セネガル (+221)',
            'RS': 'セルビア (+381)',
            'KN': 'セントクリストファー・ネイビス (+1)',
            'VC': 'セントビンセント・グレナディーン諸島 (+1)',
            'SH': 'セントヘレナ (+290)',
            'LC': 'セントルシア (+1)',
            'SO': 'ソマリア (+252)',
            'SB': 'ソロモン諸島 (+677)',
            'TC': 'タークス・カイコス諸島 (+1)',
            'TH': 'タイ (+66)',
            'TJ': 'タジキスタン (+992)',
            'TZ': 'タンザニア (+255)',
            'CZ': 'チェコ共和国 (+420)',
            'TD': 'チャド (+235)',
            'TN': 'チュニジア (+216)',
            'CL': 'チリ (+56)',
            'TV': 'ツバル (+688)',
            'DK': 'デンマーク (+45)',
            'DE': 'ドイツ (+49)',
            'TG': 'トーゴ (+228)',
            'TK': 'トケラウ (+690)',
            'DO': 'ドミニカ共和国 (+1)',
            'DM': 'ドミニカ国 (+1)',
            'TT': 'トリニダード・トバゴ (+1)',
            'TM': 'トルクメニスタン (+993)',
            'TR': 'トルコ (+90)',
            'TO': 'トンガ (+676)',
            'NG': 'ナイジェリア (+234)',
            'NR': 'ナウル (+674)',
            'NA': 'ナミビア (+264)',
            'NU': 'ニウエ島 (+683)',
            'NI': 'ニカラグア (+505)',
            'NE': 'ニジェール (+227)',
            'NC': 'ニューカレドニア (+687)',
            'NZ': 'ニュージーランド (+64)',
            'NP': 'ネパール (+977)',
            'NF': 'ノーフォーク島 (+672)',
            'NO': 'ノルウェー (+47)',
            'BH': 'バーレーン (+973)',
            'HT': 'ハイチ (+509)',
            'PK': 'パキスタン (+92)',
            'VA': 'バチカン市国 (+379)',
            'PA': 'パナマ (+507)',
            'VU': 'バヌアツ (+678)',
            'BS': 'バハマ (+1)',
            'PG': 'パプアニューギニア (+675)',
            'BM': 'バミューダ (+1)',
            'PW': 'パラオ (+680)',
            'PY': 'パラグアイ (+595)',
            'BB': 'バルバドス (+1)',
            'PS': 'パレスチナ (+970)',
            'HU': 'ハンガリー (+36)',
            'BD': 'バングラデシュ (+880)',
            'PN': 'ピトケアン諸島 (+64)',
            'FJ': 'フィジー (+679)',
            'PH': 'フィリピン (+63)',
            'FI': 'フィンランド (+358)',
            'BT': 'ブータン (+975)',
            'PR': 'プエルトリコ (+1)',
            'FO': 'フェロー諸島 (+298)',
            'FK': 'フォークランド諸島[マルビナス諸島] (+500)',
            'BR': 'ブラジル (+55)',
            'FR': 'フランス (+33)',
            'BG': 'ブルガリア (+359)',
            'BF': 'ブルキナファソ (+226)',
            'BN': 'ブルネイ (+673)',
            'BI': 'ブルンジ (+257)',
            'VN': 'ベトナム (+84)',
            'BJ': 'ベナン (+229)',
            'VE': 'ベネズエラ (+58)',
            'BY': 'ベラルーシ (+375)',
            'BZ': 'ベリーズ (+501)',
            'PE': 'ペルー (+51)',
            'BE': 'ベルギー (+32)',
            'PL': 'ポーランド (+48)',
            'BA': 'ボスニア・ヘルツェゴビナ (+387)',
            'BW': 'ボツワナ (+267)',
            'BO': 'ボリビア (+591)',
            'PT': 'ポルトガル (+351)',
            'HN': 'ホンジュラス (+504)',
            'MH': 'マーシャル諸島 (+692)',
            'MO': 'マカオ (+853)',
            'MG': 'マダガスカル (+261)',
            'YT': 'マヨット島 (+262)',
            'MW': 'マラウイ (+265)',
            'ML': 'マリ (+223)',
            'MT': 'マルタ (+356)',
            'MQ': 'マルティニーク (+596)',
            'MY': 'マレーシア (+60)',
            'IM': 'マン島 (+44)',
            'FM': 'ミクロネシア連邦 (+691)',
            'MM': 'ミャンマー (+95)',
            'MX': 'メキシコ (+52)',
            'MU': 'モーリシャス (+230)',
            'MR': 'モーリタニア (+222)',
            'MZ': 'モザンビーク (+258)',
            'MC': 'モナコ (+377)',
            'MV': 'モルジブ (+960)',
            'MD': 'モルドバ (+373)',
            'MA': 'モロッコ (+212)',
            'MN': 'モンゴル (+976)',
            'ME': 'モンテネグロ (+382)',
            'MS': 'モントセラト (+1)',
            'JO': 'ヨルダン (+962)',
            'LA': 'ラオス (+856)',
            'LV': 'ラトビア (+371)',
            'LT': 'リトアニア (+370)',
            'LY': 'リビア (+218)',
            'LI': 'リヒテンシュタイン (+423)',
            'LR': 'リベリア (+231)',
            'RO': 'ルーマニア (+40)',
            'LU': 'ルクセンブルグ (+352)',
            'RW': 'ルワンダ (+250)',
            'LS': 'レソト (+266)',
            'LB': 'レバノン (+961)',
            'RE': 'レユニオン島 (+262)',
            'RU': 'ロシア (+7)',
            'IO': '英領インド洋地域 (+246)',
            'VG': '英領ヴァージン諸島 (+1)',
            'KR': '韓国 (+82)',
            'HK': '香港 (+852)',
            'CI': '象牙海岸 (+225)',
            'EH': '西サハラ (+212)',
            'GQ': '赤道ギニア (+240)',
            'TW': '台湾 (+886)',
            'CF': '中央アフリカ共和国 (+236)',
            'CN': '中国 (+86)',
            'TL': '東ティモール (+670)',
            'ZA': '南アフリカ (+27)',
            'GS': '南ジョージア島・南サンドイッチ諸島 (+500)',
            'SS': '南スーダン (+211)',
            'GF': '仏領ギアナ (+594)',
            'PF': '仏領ポリネシア (+689)',
            'VI': '米領ヴァージン諸島 (+1)',
            'AS': '米領サモア (+1)',
        },
        //language_display_admin
        LanguageDisplay: {
            'アムハラ語': 'アムハラ語',
            'アラビア語': 'アラビア語',
            'カンボジア語': 'カンボジア語',
            '中国語': '中国語',
            'クレオール語': 'クレオール語',
            'デンマーク語': 'デンマーク語',
            'オランダの語': 'オランダの語',
            '英語': '英語',
            'エストニア語': 'エストニア語',
            'フィリピン語': 'フィリピン語',
            'フィンランド語': 'フィンランド語',
            'フラマン語': 'フラマン語',
            'フランス語': 'フランス語',
            'ドイツ語': 'ドイツ語',
            'ギリシャ語': 'ギリシャ語',
            'ヘブライ語': 'ヘブライ語',
            'インドネシア語': 'インドネシア語',
            'アイルランド語': 'アイルランド語',
            'イタリアの語': 'イタリアの語',
            '日本語': '日本語',
            '韓国語': '韓国語',
            'ラオス語': 'ラオス語',
            'ラトビア語': 'ラトビア語',
            'リトアニア語': 'リトアニア語',
            'マレーシア語': 'マレーシア語',
            'マオリ語': 'マオリ語',
            'ノルウェー語': 'ノルウェー語',
            'ペルシア語': 'ペルシア語',
            '研磨': '研磨',
            'ポルトガル': 'ポルトガル語',
            'ルーマニア語': 'ルーマニア語',
            'ロシア語': 'ロシア語',
            'スペイン語': 'スペイン語',
            'スワヒリ語': 'スワヒリ語',
            'スウェーデンの語': 'スウェーデンの語',
            'タジク語': 'タジク語',
            'タイ語': 'タイ語',
            'トルコ語': 'トルコ語',
            'ウクライナ語': 'ウクライナ語',
            'ベトナム語': 'ベトナム語',
            'ウェールズ語': 'ウェールズ語',
        }
    }
